language: elixir

elixir: '1.6.6'

addons:
  postgresql: '10'

services:
  - postgresql

before_script:
  - cd src
  - cp config/travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate

env:
  - MIX_ENV=test

script:
  - mix test
