language: elixir

elixir: '1.6.6'

addons:
  postgresql: '10'

services:
  - postgresql

before_script:
  - cd src
  - docker build -t my_hm_image .
  - docker-compose build
  - mix deps get
  - cp config/travis.exs config/test.exs
  - cd assets && npm install
  - mix do ecto.create, ecto.migrate

env:
  - MIX_ENV=test

script:
  - mix test
