required: sudo

language: elixir

elixir: '1.6.6'

addons:
  postgresql: '10'

before_install:
  - cd src
  - psql -c 'create database travis_ci_test;' -U postgres

before_script:
  - cp config/travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate

env:
  - MIX_ENV=test

script:
  - mix test
