language: elixir

elixir: '1.6.6'

addons:
  postgresql: '10'

services:
  - postgresql

before_install: cd src

before_script:
  - cp config/travis.exs config/test.exs
  - ./mix ecto.create 
  - ./mix ecto.migrate

env:
  - MIX_ENV=test

script:
  - mix test
