language: elixir

elixir: '1.6.6'

addons:
  postgresql: '10'

services:
  - docker

before_install:
  - docker build -t my_hm_image .
  - docker-compose build
  - ./mix deps.get
  - ./mix ecto.create
  - ./mix ecto.migrate
  - cd src/assets && npm install
  - cd ..
  - cp config/travis.exs config/test.exs

env:
  - MIX_ENV=test mix phx.server

script:
  - mix test
